- name: Check secrets presence
  env:
    U: ${{ secrets.DOCKERHUB_USERNAME }}
    T: ${{ secrets.DOCKERHUB_TOKEN }}
  run: |
    test -n "$U" || (echo "Missing DOCKERHUB_USERNAME secret" && exit 1)
    test -n "$T" || (echo "Missing DOCKERHUB_TOKEN secret" && exit 1)

- name: Login to Docker Hub
  uses: docker/login-action@v3
  with:
    registry: docker.io
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

- name: Build & push
  id: buildpush
  uses: docker/build-push-action@v6
  with:
    context: .
    push: true
    tags: ${{ secrets.DOCKERHUB_USERNAME }}/stitch-gcs-plus:1.0.0

- name: Print image digest
  run: echo "Pushed digest ${{ steps.buildpush.outputs.digest }}"
