name: Build and Push (Docker Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker Hub secrets
        env:
          HUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          HUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          test -n "$HUB_USER"  || (echo "Missing DOCKERHUB_USERNAME" && exit 1)
          test -n "$HUB_TOKEN" || (echo "Missing DOCKERHUB_TOKEN" && exit 1)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show Dockerfile head
        run: sed -n '1,30p' Dockerfile

      - name: Build & push
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stitch-gcs-plus:1.0.0

      - name: Print image digest
        run: echo "Pushed digest ${{ steps.buildpush.outputs.digest }}"
